name: Deliver (webitel-core)

run-name: "deliver package: ${{ inputs.commit-message }}"

on:
  workflow_dispatch:
    inputs:
      commit-message:
        type: string
        required: true
        description: Latest commit message to include in run name.

      triggered-branch:
        type: string
        required: true
        description: Triggered branch from original repository.

      artifact-actions-run-id:
        type: string
        required: true
        description: The id of the workflow run where the desired download artifact was uploaded from.

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  publish:
    name: Publish .deb package
    uses: webitel/reusable-workflows/.github/workflows/_publish-deb.yml@v1.0.6
    secrets:
      DEB_AWS_ACCESS_KEY_ID: ${{ secrets.DEB_AWS_ACCESS_KEY_ID }}
      DEB_AWS_SECRET_ACCESS_KEY: ${{ secrets.DEB_AWS_SECRET_ACCESS_KEY }}
      REPO_SIGNING_KEY: ${{ secrets.REPO_SIGNING_KEY }}
      REPO_SIGNING_KEY_PASSPHRASE: ${{ secrets.REPO_SIGNING_KEY_PASSPHRASE }}
      DELIVERY_BOT_APP_PEM: ${{ secrets.DELIVERY_BOT_APP_PEM }}

    with:
      deb-package-pattern: "webitel-core*.deb"
      deb-component: dev
      deb-codename: ${{ vars.DEB_CODENAME }}
      deb-aws-bucket-name: ${{ vars.DEB_AWS_BUCKET_NAME }}
      deb-aws-bucket-region: ${{ vars.DEB_AWS_DEFAULT_REGION }}
      github-app-id: ${{ vars.DELIVERY_BOT_APP_ID }}
      artifact-repository-owner: ${{ github.repository_owner }}
      artifact-repository: webitel.go
      artifact-actions-run-id: ${{ inputs.artifact-actions-run-id }}